### ISSUE TITLE
Multi language support request + Get region error

### ISSUE THREAD

**Issue by scottjsh** [RetherSzu/valorant-daily-shop#1] opened 2024-04-22 12:56 UTC
Your source code is so neat and good. And I want to contribute on you project.
How about add multi language support? I can add Korean.

**Comment by scottjsh** [comment] 2024-04-22 13:00
Plus I cannot find expo/tsconfig.base

**Comment by scottjsh** [comment] 2024-04-22 13:12
One more, I can't login with your app.

My Valorant region is KR.

https://github.com/RetherSzu/valorant-daily-shop/assets/62782800/728a3954-3722-4aee-8155-a109a71967b2

**Comment by scottjsh** [comment] 2024-04-23 02:35
When I debug the app, `pd.an.a.pvp.net` appers.
My account region is KR.
I think there's some problem on `/userinfo`

**Comment by RetherSzu** [comment] 2024-04-23 10:58
Hello @scottjsh,

Thank you for your feedback and for pointing out this issue.

It appears that the problem was caused by my oversight in not retrieving the region information from a previous request. I've implemented a fix for this in the latest commit.

However, I haven't been able to test the fix myself yet. I would appreciate it if you could download the updated version of the app from the link below and see if it resolves the issue on your end. Here is the link to the application with the applied fix:

[Download the updated app here](https://drive.google.com/file/d/15gj5i1eBKjkDFEm-TVVhSPkboeFOjkM-/view?usp=sharing)

Please let me know if you encounter any further problems or if there's anything else I can assist with.

Thanks again for your help in improving the app!

**Comment by scottjsh** [comment] 2024-04-23 11:05
Thank you for your reply. 

App works nicely. But skin name is too small.

**Comment by RetherSzu** [comment] 2024-04-23 11:14
Thanks for your feedback! I'll try to enlarge the skin name so it's more visible. I appreciate your contribution!

**Comment by scottjsh** [comment] 2024-04-23 13:59
I'm talking about the "oni" part of "oni phantom". please refer to this.

**Closed** 2024-04-25 20:44 UTC
